name: Dummy Deploy
on:
  workflow_call:
    inputs:
      number: 
        description: The number which will be logged
        required: true
        type: number
jobs:
  deploy:
      runs-on: ubuntu-latest  
      steps:
        - run: echo ${{ inputs.number }} 
        