name: Smoke Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright Tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx playwright test --grep "@smoke" --project=chromium --project=api --trace on
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-test-result
          path: playwright-report
  output_test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts from previous job
        uses: actions/download-artifact@v3
        with:
          name: playwright-test-result
      - run: ls
      - name: Download artifact
        run: echo "Deploying..."
